$text_color = rgba(dce5dcFF)
$text_muted_color = rgba(bbcabdBB)
$shadow_color = rgba(000000CC)

$entry_background_color = rgba(1a211cAA)
$entry_border_color = rgba(859488FF)
$entry_color = rgba(dce5dcFF)

$font_family = IosevkaTerm NF Medium
$font_family_clock = IosevkaTerm NF Medium
$font_material_symbols = Material Symbols Rounded