$text_color = rgba(eee1cfFF)
$text_muted_color = rgba(d5c4aaBB)
$shadow_color = rgba(000000CC)
$entry_background_color = rgba(080808AA)
$entry_border_color = rgba(d9b9ffFF)  # Full gold, no alpha
$entry_color = rgba(eee1cfFF)
$primary_glow = rgba(d9b9ffDD)  # Bright gold for highlights
$font_family = IosevkaTerm NF Medium
$font_family_clock = IosevkaTerm NF Medium
$font_material_symbols = Material Symbols Rounded