[Personal]
source        = imaps://alexmarumo16%40gmail.com@imap.gmail.com:993
outgoing      = smtp://alexmarumo16%40gmail.com@smtp.gmail.com:587
source-cred-cmd = pass gmail/emailpass
outgoing-cred-cmd = pass gmail/emailpass
default       = INBOX
from          = Alex Marumo <alexmarumo16@gmail.com>
cache-headers = true
