# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
windowrule = opacity 0.90 override 0.75 override, match:class .*
windowrule = opacity 1.00 override 0.90 override, match:class ^(zen)$
windowrule = opacity 0.70 override 0.50 override, match:class ^(kitty)$
windowrule = opacity 1.00 override 0.90 override, match:class ^(gimp)$
windowrule = opacity 1.00 override 0.90 override, match:class ^(rawtherapee)$

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

