$background  = rgba(0E1112ff)
$foreground  = rgba(F5FCFDff)
$color0      = rgba(37393Aff)
$color1      = rgba(021316ff)
$color2      = rgba(06264Bff)
$color3      = rgba(1A5370ff)
$color4      = rgba(428499ff)
$color5      = rgba(7EC0D7ff)
$color6      = rgba(E2F5FAff)
$color7      = rgba(E8F2F4ff)
$color8      = rgba(A2A9ABff)
$color9      = rgba(021316ff)
$color10     = rgba(06264Bff)
$color11     = rgba(1A5370ff)
$color12     = rgba(428499ff)
$color13     = rgba(7EC0D7ff)
$color14     = rgba(E2F5FAff)
$color15     = rgba(E8F2F4ff)

$primary     = rgba(7EC0D7ff)
$secondary   = rgba(E2F5FAff)
