backend = "kmeans"
color_space = "lch"
threshold = 1
palette = "dark-comp16"

[filters]
percent = 90
brightness = -2
saturation = 80

[templates]
# AGS colors
ags-colors.target = "~/.config/ags/colors.scss"
ags-colors.template = "ags-colors.scss"

# Hyprland colors
hypr-colors.target = "~/.config/hypr/colors.conf"
hypr-colors.template = "hypr-colors.conf"

# Kitty theme
kitty-colors.target = "~/.config/kitty/current-theme.conf"
kitty-colors.template = "kitty-colors.conf"

# Tuigreet theme
greetd.target = "/etc/greetd/config.toml"
greetd.template = "greetd-config.toml"

# Wlogout theme
wlogout.target = "~/.config/wlogout/style.css"
wlogout.template = "wlogout-style.css"

# Hyprlock theme
hyprlock-colors.target = "~/.config/hypr/hyprlock/colors.conf"
hyprlock-colors.template = "hyprlock-colors.conf"

[pywal]
enabled = false
