# ── DBus / Environment ──
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# ── Visuals / Appearance ──
exec-once = awww-daemon --format xrgb &
exec-once = sleep 1 && awww img $(cat ~/.config/waypaper/config.ini | grep wallpaper | cut -d'=' -f2)
exec-once = hyprctl setcursor Bibata-Modern-Ice 24 &
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# ── AGS (launch ASAP, after tiny delay) ──
exec-once = bash -c 'sleep 0.2 && ags run --gtk 4'
exec-once = bash -c 'sleep 2 && bash ~/.config/ags/scripts/reload-ags.sh >> /tmp/reload-ags.log 2>&1'

# ── Background Services ──
exec-once = bash -c 'sleep 2 && hypridle'
exec-once = bash -c 'sleep 2 && easyeffects --gapplication-service'
exec-once = bash -c 'sleep 3 && wl-paste --type text --watch cliphist store'
exec-once = bash -c 'sleep 3 && wl-paste --type image --watch cliphist store'
exec-once = bash -c '~/.config/ags/scripts/battery-notify.sh'

# ── Activate Arch ──
exec-once = LD_PRELOAD=/usr/lib/libgtk4-layer-shell.so python3 ~/.config/ags/scripts/activate-linux.py
