# hyprland.conf
# Sources hyprland/ for defaults, custom/ for your overrides

# Environment variables
source=~/.config/hypr/hyprland/env.conf
source=~/.config/hypr/custom/env.conf

# Core
source=~/.config/hypr/hyprland/execs.conf
source=~/.config/hypr/hyprland/general.conf
source=~/.config/hypr/hyprland/rules.conf
source=~/.config/hypr/hyprland/keybinds.conf

# Your overrides
source=~/.config/hypr/custom/execs.conf
source=~/.config/hypr/custom/general.conf
source=~/.config/hypr/custom/rules.conf
source=~/.config/hypr/custom/keybinds.conf

# Display config
source=~/.config/hypr/monitors.conf
source=~/.config/hypr/workspaces.conf